### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by b4j4** [RalphHogenbirk/WiPy-PIR-Domoticz#1]
Do you use Pymakr?
I try to run on the board with Pymakr and i got this:

![captura de ecra de 2017-03-01 01-28-44](https://cloud.githubusercontent.com/assets/10621831/23442187/f7cc593c-fe1e-11e6-9b02-412cf4ecea60.png)

**Comment by RalphHogenbirk** [comment]
Hi Steeven,

It seems like you didn’t upload the domoticz.py file to the board. First do a sync action or manual ftp to get it on there, then try again.

**Comment by b4j4** [comment]
Thanks, it works.
